import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime'
import { Toaster } from '@/components/ui/toaster'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import { ThemeProvider } from '@/components/theme/theme-provider'
var inter = Inter({ subsets: ['latin'] })
export var metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout(_a) {
    var children = _a.children
    return _jsx('html', {
        lang: 'pt-br',
        children: _jsx('body', {
            className: inter.className,
            children: _jsxs(ThemeProvider, {
                attribute: 'class',
                children: [children, _jsx(Toaster, {})],
            }),
        }),
    })
}
